### ISSUE TITLE
Nether terrain won't generate after resetting world_nether

### ISSUE THREAD

**Issue by timsandtoms** [cybertiger/Bukkit-InstantReset#6]
![2015-06-09_14 56 20](https://cloud.githubusercontent.com/assets/7901963/8070670/e9e77d54-0eb7-11e5-8f04-2a3ffeb3a2fb.png)
I removed world_nether and world_the_end from server.properties and bukkit.yml, generated fresh copies and made sure they were able to be teleported to and had chunks generated, then copied the world saves to /InstantReset/templates/<world name>, added them to the config, restarted the server to apply config changes, and restarted the server again to test if it reset. world_the_end works fine, but world_nether does what's pictured above, and won't let new chunks generate when someone makes a nether portal. Here's a copy of my config.yml.

# Where to look for world templates.
templatedir: templates
worlddir: worlds
resetOnRestart: true
worlds:
  world_the_end:
    environment: THE_END
    difficulty: HARD
    template: world_the_end
  world_nether:
    environment: NETHER
    difficulty: HARD
    template: world_nether

**Comment by cybertiger** [comment]
Worlds must be pregenerate. I'm guessing your nether world worked but only in the area around spawn where it'd been pregenerated. The end of course is entirely pregenerated, so you won't notice any difference.

Generator support is a new feature (which probably isn't too difficult to add).

The problem is that generating worlds is slow, and the vast majority of people probably should be pregenerating the whole world they wish to reset, to avoid having to generate new chunks every time it is reset. (World size has little or no effect on reset time with InstantReset).

So whilst I could add arbitrary generator support, it's not actually that useful to anyone.
